# Generated by Django 5.0.3 on 2026-06-10 12:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('school', 'School / University'), ('hospital', 'Hospital / Clinic'), ('business', 'Business'), ('charity', 'Charity / NGO')], max_length=50)),
                ('country', models.CharField(choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('GB', 'United Kingdom'), ('US', 'United States')], max_length=2)),
                ('address', models.TextField(blank=True)),
                ('account_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('country', models.CharField(blank=True, choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('GB', 'United Kingdom'), ('US', 'United States')], max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_vendor', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_type', models.CharField(choices=[('person', 'Individual'), ('institution', 'Institution')], default='person', max_length=15)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_account', models.CharField(blank=True, max_length=50)),
                ('recipient_bank', models.CharField(blank=True, max_length=255)),
                ('send_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('send_currency', models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'US Dollar'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi')], max_length=3)),
                ('receive_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('receive_currency', models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'US Dollar'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi')], max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fee_type', models.CharField(choices=[('sender', 'Sender pays full fee'), ('recipient', 'Deduct fee from recipient amount'), ('split', 'Split fee between both parties')], default='sender', max_length=15)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sender_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recipient_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shield_applied', models.BooleanField(default=False)),
                ('rate_at_confirm', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=15)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='main.institution')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(choices=[('GBP_NGN', 'GBP → NGN'), ('USD_NGN', 'USD → NGN'), ('GBP_GHS', 'GBP → GHS'), ('USD_GHS', 'USD → GHS')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='main.exchangevendor')),
            ],
            options={
                'unique_together': {('vendor', 'currency_pair')},
            },
        ),
    ]
